### ISSUE TITLE
Eval sometimes returns null during concurrent use

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-service-armadillo#101]
Two users, assign D = 2, and keep repeating debug D.
Occasionally the debug will return null and the session detach will fail.
With a single user, all is well

See the load test
[null-eval.jmx.zip](https://github.com/molgenis/molgenis-service-armadillo/files/5168162/null-eval.jmx.zip)

**Comment by fdlk** [comment]
Happens when two sessions detach simultaneously:
```
18:43:00.070 [pool-1-thread-4|F48140CC] DEBUG o.m.r.service.RExecutorServiceImpl - Evaluate D
18:43:00.070 [pool-1-thread-3|FE02B314] DEBUG o.m.r.service.RExecutorServiceImpl - Evaluate D
18:43:00.113 [pool-1-thread-4|] DEBUG o.m.armadillo.ArmadilloSession - Detached session, port = Optional[53002]
18:43:00.114 [pool-1-thread-3|] ERROR o.m.armadillo.ArmadilloSession - Failed to detach connection
org.rosuda.REngine.Rserve.RserveException: Cannot detach, request status: session detach failed
        at org.rosuda.REngine.Rserve.RConnection.detach(RConnection.java:388)
        at org.molgenis.armadillo.ArmadilloSession.tryDetachRConnection(ArmadilloSession.java:56)
        at org.molgenis.armadillo.ArmadilloSession.execute(ArmadilloSession.java:36)
        at org.molgenis.armadillo.command.impl.CommandsImpl.lambda$schedule$1(CommandsImpl.java:76)
        at org.molgenis.armadillo.command.impl.CommandsImpl.lambda$withCurrentSecurityContext$2(CommandsImpl.java:88)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
