### ISSUE TITLE
Trying to connect to docker container shows exception as INFO

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#505]
We try 10 times in increasing sleeping times (1,2,4,8,10 seconds)

The level could be lowered to DEBUG

```log
09:33:07.794 [http-nio-8080-exec-1|70F872C4] DEBUG o.m.r.rserve.RserveConnectionFactory - Trying to connect to instance: [ localhost ] on [ 8085 ]
09:33:07.795 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.r.b.ExponentialBackOffPolicy - Sleeping for 1000
09:33:08.796 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.retry.support.RetryTemplate - Checking for rethrow: count=1
09:33:08.796 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.retry.support.RetryTemplate - Retry: count=1
09:33:08.796 [http-nio-8080-exec-1|70F872C4] DEBUG o.m.r.rock.RockConnectionFactory - Trying to connect to instance: [ localhost ] on [ 8085 ]
09:33:08.807 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.web.client.RestTemplate - HTTP POST http://localhost:8085/r/sessions
09:33:08.809 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.web.client.RestTemplate - Accept=[application/json, application/*+json]
09:33:08.811 [http-nio-8080-exec-1|70F872C4] INFO  o.m.r.RServerConnectionFactory - Not a Rock server [org.molgenis.r.rock.RockServerException: Failure when opening a Rock R session], trying Rserve...
org.molgenis.r.exceptions.ConnectionCreationFailedException: org.molgenis.r.rock.RockServerException: Failure when opening a Rock R session
	at org.molgenis.r.rock.RockConnectionFactory.tryCreateConnection(RockConnectionFactory.java:39)
	at org.molgenis.r.RServerConnectionFactory.tryCreateConnection(RServerConnectionFactory.java:22)
	at org.molgenis.r.RServerConnectionFactory$$FastClassBySpringCGLIB$$4888b387.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
...
```

after 10 tries we TRACE exception which is lowest level logging so OK

```
09:34:13.049 [http-nio-8080-exec-1|70F872C4] DEBUG o.m.r.rserve.RserveConnectionFactory - Trying to connect to instance: [ localhost ] on [ 8085 ]
09:34:13.052 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.retry.support.RetryTemplate - Checking for rethrow: count=10
09:34:13.052 [http-nio-8080-exec-1|70F872C4] DEBUG o.s.retry.support.RetryTemplate - Retry failed last attempt: count=10
09:34:13.052 [http-nio-8080-exec-1|70F872C4] INFO  o.m.armadillo.audit.AuditLogger - AuditEvent [timestamp=2023-10-05T07:34:13.052573Z, principal=c.g.w.m.tolboom@umcg.nl, type=SELECT_PROFILE_FAILURE, data={sessionId=BEB28F0D587B0193CF9B289370F872C4, message=org.rosuda.REngine.Rserve.RserveException: Cannot connect: Handshake failed: expected 32 bytes header, got -1, type=org.molgenis.r.exceptions.ConnectionCreationFailedException, selectedProfile=rock, roles=[ROLE_SU]}]

09:34:13.056 [http-nio-8080-exec-1|70F872C4] TRACE o.m.a.interceptor.MDCInterceptor - afterCompletion

09:34:13.057 [http-nio-8080-exec-1|] TRACE o.s.web.servlet.DispatcherServlet - Failed to complete request
org.molgenis.r.exceptions.ConnectionCreationFailedException: org.rosuda.REngine.Rserve.RserveException: Cannot connect: Handshake failed: expected 32 bytes header, got -1
	at org.molgenis.r.rserve.RserveConnectionFactory.tryCreateConnection(RserveConnectionFactory.java:44)
...
```

**Comment by marikaris** [comment]
Completely refactored the code. Haven't seen this anymore
