### ISSUE TITLE
Session detach sometimes fails

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis-service-armadillo#61]
## How to reproduce
When multiple users are concurrently logging in, loading tables and logging out, at some point a session fails to detach.
```
13:24:50.942 [pool-1-thread-61|] ERROR o.m.armadillo.ArmadilloSession - Failed to detach connection
org.rosuda.REngine.Rserve.RserveException: Cannot detach, request status: session detach failed
	at org.rosuda.REngine.Rserve.RConnection.detach(RConnection.java:388)
	at org.molgenis.armadillo.ArmadilloSession.tryDetachRConnection(ArmadilloSession.java:37)
	at org.molgenis.armadillo.ArmadilloSession.execute(ArmadilloSession.java:31)
	at org.molgenis.armadillo.command.impl.CommandsImpl.lambda$schedule$1(CommandsImpl.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Rserve debug logs are massive but you can contain the damage a bit by filtering them on `session:`:
`docker logs -f <the id> | grep session`

And this error is on the RServe side visible as `session: can't find available prot to listed on.`

**Comment by fdlk** [comment]
We took a look at the RServe code and it picks a random port from the range and then keeps increasing port numbers while they are in use until it ends up outside the range. Unfortunately, because the search can start at 53199, if that one is already taken it'll immediately conclude that the port is not in use. This is obviously asking for trouble but probably works most of the time in the original codebase because its port range is 32k-64k whereas ours is just 53000 to 53200.

So the first step is to simply always start at port 52000 and see if that helps.

**Comment by fdlk** [comment]
On our side, we can retry connecting and check if that helps. My first impression is that there is something else going on (improper closing of the socket on detaching?) that causes more and more ports to become unavailable.

**Comment by fdlk** [comment]
Yes, logout didn't log out the session!
